version: '3.8'

networks:
  tp1network:
    name: tp1network
    driver: bridge

services:
  database:
    image: postgres:14.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    networks:
      - tp1network
  bdtp1:
    build: .
    depends_on:
     - database
    networks:
      - tp1network